FROM ghcr.io/tbistr/texlive-full:v3.0

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
    nodejs npm && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g \
    textlint \
    textlint-rule-preset-ja-spacing textlint-rule-preset-ja-technical-writing \
    textlint-plugin-latex2e
